name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Allow the action to use the automatically provided GITHUB_TOKEN
          # to push commits created by the deploy action.
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          echo "Node version:" && node --version
          echo "NPM version:" && npm --version
          # Use npm install as fallback when package-lock.json isn't present on remote
          npm install --no-audit --no-fund

      - name: Build
        run: npm run build --if-present

      - name: Verify build output
        run: |
          echo "Listing workspace files for debugging"
          ls -la
          echo "Checking dist directory"
          if [ -d "./dist" ]; then
            echo "dist exists. Contents:" && ls -la ./dist || true
          else
            echo "ERROR: build didn't produce ./dist. Failing early with logs above." && exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
